-- 生辰邀函 · 名单种子数据（由 gen_seed.py 从 xlsx 生成）
-- 用法：在 Supabase → SQL Editor 粘贴全部内容运行。
-- 说明：已写邀函全文者写入原文；空白者写 NULL，前端套默认古风兜底。
-- ON CONFLICT 保证重跑不会报错；COALESCE 保证不会把已写文案覆盖成空。

-- 若需重跑：确保 invitations 表已存在且 name 为主键；已存在的名字会被跳过，不会覆盖您后来填写的文案。
INSERT INTO public.invitations (name, invitation_text) VALUES ('李文静', '静女其姝，俟我于城隅。大咖生辰，诚邀袍姝线上赴宴！<p class="sign">—— 陈山石 谨邀</p>') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('张翀赫', '一飞翀昊苍，齐红日煊赫。特邀翀赫学长线上赴宴！<p class="sign">—— 陈山石 谨邀</p>') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('张颖', '草木嫩发，穗颖春三月。诚邀张颖同学线上赴宴！<p class="sign">—— 陈山石 谨邀</p>') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('陈彦彤', '金光闪闪，1695的彤彤大人，小的邀请您前往线上赴宴！<p class="sign">—— 陈山石 谨邀</p>') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('楚嫣涵', '笑语嫣然，楚硕有内涵。小弟满怀赤诚地邀请您线上赴宴！<p class="sign">—— 陈山石 谨邀</p>') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('代鹏', '九万里风，无己无功无名，特邀鸟哥大圣前来线上赴宴！<p class="sign">—— 陈山石 谨邀</p>') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('邓宇恬', '宇宙渺远无际，幸好我能碰到你。羽天和珂霖是一辈子的好朋友！<p class="sign">—— 陈山石 谨邀</p>') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('董秋书', '秋夜微凉，我致书与你：诚邀董秋书同学参加我的线上宴会！<p class="sign">—— 陈山石 谨邀</p>') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('杜唐雨', '小雨如酥润，唐雨似仙神，无敌努力的豆哥请来线上赴宴吧！<p class="sign">—— 陈山石 谨邀</p>') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('尹飞扬', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('付雨佳', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('王明磊', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('关昊宇', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('肖宇杰', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('郭俊杰', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('何律江', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('何睿祺', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('黄虹菡', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('黄璐', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('贾华东', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('蒋贤一', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('江自豪', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('胡怀月', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('雷诗曼', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('梁焕祺', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('李鹏坤', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('李诗颖', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('刘舒颜', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('刘芸君', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('刘紫涵', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('李婉婷', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('李优静', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('罗阡芸', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('罗文诗', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('张苗苗', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('刘湘', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('陶圆', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('王士凡', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('袁子仪', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('任思睿', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('张诗韵', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('汤楚岩', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('张越', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('王福灵', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('王梦原', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('王潇珩', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('王奕涵', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('王梓玥', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('魏欣怡', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('孙雯', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('肖红云', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('熊曼君', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('袁启旋', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('杨钧淇', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('闫译琏', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('王熠航', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('易聪', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('袁敬明', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('袁梦', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('张诗作', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('张哲瑞', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('赵凤莲', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('赵江波', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('赵金双', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('祝华进', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('张紫凝', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('郑善铭', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('周以勒', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('韦德华', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('高京一', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('王梦琪', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('张秋', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('王子辰', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.invitations (name, invitation_text) VALUES ('马湘淼', NULL) ON CONFLICT (name) DO NOTHING;
